### ISSUE TITLE
Usage shortcut for Inc/Dec number

### ISSUE THREAD

**Issue by faridulhassan** [jeremyworboys/inc-dec-value#3]
Can you tell me please how to use this plugin for increment/decrement numbers? Mainly I need the shortcut.

**Comment by ildarkhasanshin** [comment]
put cursor on number
- alt+up/down (example 4437 -> 4438)
- ctrl+alt+up/down (example 4437 -> 4447)
- meta(win)+ctrl+alt+up/down (example 4437 -> 4537)
- or ctrl+shift+a and enter inc or dec

change hotkeys
file -> settings -> keymap -> plug-ins -> inc dec value

**Comment by jeremyworboys** [comment]
Exactly as @ildarkhasanshin said.
